    - name: Application sysctl
      ansible.posix.sysctl:
        name: '{{ item.key }}'
        value: '{{ item.value }}'
        sysctl_set: yes
        sysctl_file: /etc/sysctl.d/98-hardened.conf
        reload: yes
      with_dict: '{{ sysctl_config }}'