    - name: Disable modules at boot
      ansible.builtin.template:
        src: boot.cfg.j2
        dest: /etc/default/grub.d/boot.cfg
        owner: root
        group: root
        mode: '0700'
        force: yes